browser =chrome
URL = https://demowebshop.tricentis.com/login
driverProperty = webdriver.chrome.driver
driverPath = C:\\Software\\chromedriver.exe
ExcelSheetName= Sheet1
log4JPropertiesFileLoc = C:\\Users\\nshinde\\eclipse-workspace\\WebShop\\log4j.properties